#!/bin/bash

export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export STATUS_REPO='git@github.com:powerline/fonts.git'
export VUNDLE_REPO='git@github.com:VundleVim/Vundle.vim.git'
export VUNDLE_PATH="${DIR}/.vim/bundle/Vundle.vim"

cd "${HOME}"

test -d .vim -a ! -L .vim && rm -rfi .vim
ln -fs "${DIR}/.vim"
ln -fs "${DIR}/.vimrc"
ln -fs "${DIR}/.gitignore_global"

# Setup global Git ignore config.
git config --global core.excludesfile "${HOME}/.gitignore_global"

# Setup Vundle package manager.
test ! -e ${VUNDLE_PATH} && git clone "${VUNDLE_REPO}" "${VUNDLE_PATH}"
vim +PluginInstall +qall

# Setup status line fonts for Vim.
fonts="$(basename $STATUS_REPO)"
fonts="${DIR}/${fonts%.*}"
test ! -e "${fonts}" && git clone "${STATUS_REPO}" "${fonts}" \
                     && "${fonts}/install.sh"

if [ "$(uname)" == 'Darwin' ]; then
    "${DIR}/setup-mac"
fi
