#!/bin/bash

export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export STATUS_REPO='https://github.com/powerline/fonts.git'
export VUNDLE_REPO='https://github.com/VundleVim/Vundle.vim.git'
export VUNDLE_PATH="${DIR}/.vim/bundle/Vundle.vim"

function run() {
    name=${1}
    echo "--> \`${name}\`"
    eval "${name}"
}

function input() {
    name=${1}
    question="${2}"
    if [ -z "$(eval ${name})" ]; then
        echo "${question}"
        read -r value
        run "${name} \"${value}\""
    fi
}

function delete_if_not_symlink_dir() {
    test -d "${1}" -a ! -L "${1}" && rm -rf "${1}"
}

sudo sh -c "`curl https://babushka.me/up`" </dev/null

cd "${HOME}"

delete_if_not_symlink_dir .vim
delete_if_not_symlink_dir .babushka

ln -fs "${DIR}/.vim"
ln -fs "${DIR}/.vimrc"
ln -fs "${DIR}/.gitignore_global"
ln -fs "${DIR}/.aliases"
ln -fs "${DIR}/.zshrc"
ln -fs "${DIR}/.bashrc"
ln -fs "${DIR}/.bash_login"
ln -fs "${DIR}/.babushka"
ln -fs "${DIR}/.tmux.conf"
ln -fs "${DIR}/.gnupg/gpg-agent.conf"

# TODO(maros): Convert everything in this setup script to Babuska deps.
babushka dotfiles

if [ "${?}" -ne 0 ]; then
    exit 1
fi

# Setup global Git ignore config.
git config --global core.excludesfile "${HOME}/.gitignore_global"
git config --global core.editor vim
git config --global push.default simple

input "git config --global user.name"  "Git: Enter first and last name:"
input "git config --global user.email" "Git: Enter email:"

# Setup Vundle package manager.
test ! -e ${VUNDLE_PATH} && git clone "${VUNDLE_REPO}" "${VUNDLE_PATH}"
vim +PluginInstall +qall

# Setup status line fonts for Vim.
fonts="$(basename $STATUS_REPO)"
fonts="${DIR}/${fonts%.*}"
test ! -e "${fonts}" && git clone "${STATUS_REPO}" "${fonts}"
"${fonts}/install.sh"

if [ "$(uname)" == 'Darwin' ]; then
    "${DIR}/setup-mac"
fi

if [ "$(which zsh)" ]; then
    run "chsh -s $(which zsh)"
fi
